### ISSUE TITLE
Missing @Component or @Configuration on class

### ISSUE THREAD

**Issue by oneturkmen** [zhouhuan751312/J2EEFAST#8]
The following class uses `@Bean` on a field, but is missing `@Component` or `@Configuration` annotation on the class. Is it intentional?

https://github.com/zhouhuan751312/J2EEFAST/blob/7e18be194229211eca3fbbf8ef7b482e4fb481df/fast-common/src/main/java/com/j2eefast/common/core/thread/ThreadPoolConfig.java#L16

Reference: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Bean.html

**Comment by zhouhuan751312** [comment]
谢谢提醒！ 此处写错了，无用类可以删除！
